<?php

namespace NigelCunningham\Puphpeteer\Resources;

use NigelCunningham\Puphpeteer\Traits\AliasesSelectionMethods;
use NigelCunningham\Puphpeteer\Traits\AliasesEvaluationMethods;

/**
 * @property-read \NigelCunningham\Puphpeteer\Resources\Keyboard keyboard
 * @property-read \NigelCunningham\Puphpeteer\Resources\Touchscreen touchscreen
 * @property-read \NigelCunningham\Puphpeteer\Resources\Coverage coverage
 * @property-read \NigelCunningham\Puphpeteer\Resources\Tracing tracing
 * @property-read \NigelCunningham\Puphpeteer\Resources\Accessibility accessibility
 * @property-read \NigelCunningham\Puphpeteer\Resources\Mouse mouse
 * @method bool isDragInterceptionEnabled()
 * @method-extended bool isDragInterceptionEnabled()
 * @method bool isJavaScriptEnabled()
 * @method-extended bool isJavaScriptEnabled()
 * @method \NigelCunningham\Puphpeteer\Resources\EventEmitter on(mixed $eventName, \NigelCunningham\Rialto\Data\JsFunction $handler)
 * @method-extended \NigelCunningham\Puphpeteer\Resources\EventEmitter on(mixed $eventName, callable(mixed $event): void|\NigelCunningham\Rialto\Data\JsFunction $handler)
 * @method \NigelCunningham\Puphpeteer\Resources\EventEmitter once(mixed $eventName, \NigelCunningham\Rialto\Data\JsFunction $handler)
 * @method-extended \NigelCunningham\Puphpeteer\Resources\EventEmitter once(mixed $eventName, callable(mixed $event): void|\NigelCunningham\Rialto\Data\JsFunction $handler)
 * @method \NigelCunningham\Puphpeteer\Resources\EventEmitter off(mixed $eventName, \NigelCunningham\Rialto\Data\JsFunction $handler)
 * @method-extended \NigelCunningham\Puphpeteer\Resources\EventEmitter off(mixed $eventName, callable(mixed $event): void|\NigelCunningham\Rialto\Data\JsFunction $handler)
 * @method \NigelCunningham\Puphpeteer\Resources\FileChooser waitForFileChooser(array $options = [])
 * @method-extended \NigelCunningham\Puphpeteer\Resources\FileChooser waitForFileChooser(array<string, mixed> $options = null)
 * @method void setGeolocation(array $options)
 * @method-extended void setGeolocation(array<string, mixed> $options)
 * @method \NigelCunningham\Puphpeteer\Resources\Target target()
 * @method-extended \NigelCunningham\Puphpeteer\Resources\Target target()
 * @method \NigelCunningham\Puphpeteer\Resources\Browser browser()
 * @method-extended \NigelCunningham\Puphpeteer\Resources\Browser browser()
 * @method \NigelCunningham\Puphpeteer\Resources\BrowserContext browserContext()
 * @method-extended \NigelCunningham\Puphpeteer\Resources\BrowserContext browserContext()
 * @method \NigelCunningham\Puphpeteer\Resources\CDPSession client()
 * @method-extended \NigelCunningham\Puphpeteer\Resources\CDPSession client()
 * @method \NigelCunningham\Puphpeteer\Resources\Frame mainFrame()
 * @method-extended \NigelCunningham\Puphpeteer\Resources\Frame mainFrame()
 * @method \NigelCunningham\Puphpeteer\Resources\Frame[] frames()
 * @method-extended \NigelCunningham\Puphpeteer\Resources\Frame[] frames()
 * @method \NigelCunningham\Puphpeteer\Resources\WebWorker[] workers()
 * @method-extended \NigelCunningham\Puphpeteer\Resources\WebWorker[] workers()
 * @method void setRequestInterception(bool $value)
 * @method-extended void setRequestInterception(bool $value)
 * @method void setDragInterception(bool $enabled)
 * @method-extended void setDragInterception(bool $enabled)
 * @method void setOfflineMode(bool $enabled)
 * @method-extended void setOfflineMode(bool $enabled)
 * @method void emulateNetworkConditions(mixed|null $networkConditions)
 * @method-extended void emulateNetworkConditions(mixed|null $networkConditions)
 * @method void setDefaultNavigationTimeout(float $timeout)
 * @method-extended void setDefaultNavigationTimeout(float $timeout)
 * @method void setDefaultTimeout(float $timeout)
 * @method-extended void setDefaultTimeout(float $timeout)
 * @method mixed evaluateHandle(\NigelCunningham\Rialto\Data\JsFunction|string $pageFunction, int|float|string|bool|null|array|\NigelCunningham\Puphpeteer\Resources\JSHandle ...$args)
 * @method-extended mixed evaluateHandle(\NigelCunningham\Rialto\Data\JsFunction|callable|string $pageFunction, int|float|string|bool|null|array|\NigelCunningham\Puphpeteer\Resources\JSHandle ...$args)
 * @method \NigelCunningham\Puphpeteer\Resources\JSHandle queryObjects(\NigelCunningham\Puphpeteer\Resources\JSHandle $prototypeHandle)
 * @method-extended \NigelCunningham\Puphpeteer\Resources\JSHandle queryObjects(\NigelCunningham\Puphpeteer\Resources\JSHandle $prototypeHandle)
 * @method mixed[] cookies(string ...$urls)
 * @method-extended mixed[] cookies(string ...$urls)
 * @method void deleteCookie(mixed ...$cookies)
 * @method-extended void deleteCookie(mixed ...$cookies)
 * @method void setCookie(mixed ...$cookies)
 * @method-extended void setCookie(mixed ...$cookies)
 * @method \NigelCunningham\Puphpeteer\Resources\ElementHandle addScriptTag(array $options)
 * @method-extended \NigelCunningham\Puphpeteer\Resources\ElementHandle addScriptTag(array{ url: string, path: string, content: string, type: string, id: string } $options)
 * @method \NigelCunningham\Puphpeteer\Resources\ElementHandle addStyleTag(array $options)
 * @method-extended \NigelCunningham\Puphpeteer\Resources\ElementHandle addStyleTag(array{ url: string, path: string, content: string } $options)
 * @method void exposeFunction(string $name, \NigelCunningham\Rialto\Data\JsFunction|array $puppeteerFunction)
 * @method-extended void exposeFunction(string $name, callable|\NigelCunningham\Rialto\Data\JsFunction|array{ default: callable|\NigelCunningham\Rialto\Data\JsFunction } $puppeteerFunction)
 * @method void authenticate(mixed $credentials)
 * @method-extended void authenticate(mixed $credentials)
 * @method void setExtraHTTPHeaders(array|string[]|string[] $headers)
 * @method-extended void setExtraHTTPHeaders(array|string[]|string[] $headers)
 * @method void setUserAgent(string $userAgent, mixed $userAgentMetadata = null)
 * @method-extended void setUserAgent(string $userAgent, mixed $userAgentMetadata = null)
 * @method mixed metrics()
 * @method-extended mixed metrics()
 * @method string url()
 * @method-extended string url()
 * @method string content()
 * @method-extended string content()
 * @method void setContent(string $html, array $options = [])
 * @method-extended void setContent(string $html, array $options = [])
 * @method \NigelCunningham\Puphpeteer\Resources\HTTPResponse goto(string $url, array $options = [])
 * @method-extended \NigelCunningham\Puphpeteer\Resources\HTTPResponse goto(string $url, array $options = [])
 * @method \NigelCunningham\Puphpeteer\Resources\HTTPResponse|null reload(array $options = [])
 * @method-extended \NigelCunningham\Puphpeteer\Resources\HTTPResponse|null reload(array $options = [])
 * @method \NigelCunningham\Puphpeteer\Resources\HTTPResponse|null waitForNavigation(array $options = [])
 * @method-extended \NigelCunningham\Puphpeteer\Resources\HTTPResponse|null waitForNavigation(array $options = [])
 * @method \NigelCunningham\Puphpeteer\Resources\HTTPRequest waitForRequest(string|\NigelCunningham\Rialto\Data\JsFunction $urlOrPredicate, array $options = [])
 * @method-extended \NigelCunningham\Puphpeteer\Resources\HTTPRequest waitForRequest(string|callable(): |\NigelCunningham\Rialto\Data\JsFunction $urlOrPredicate, array $options = [])
 * @method \NigelCunningham\Puphpeteer\Resources\HTTPResponse waitForResponse(string|\NigelCunningham\Rialto\Data\JsFunction $urlOrPredicate, array $options = [])
 * @method-extended \NigelCunningham\Puphpeteer\Resources\HTTPResponse waitForResponse(string|callable(): |\NigelCunningham\Rialto\Data\JsFunction $urlOrPredicate, aray $options = [])
 * @method void waitForNetworkIdle(array $options = [])
 * @method-extended void waitForNetworkIdle(array $options = [])
 * @method \NigelCunningham\Puphpeteer\Resources\Frame waitForFrame(string|\NigelCunningham\Rialto\Data\JsFunction $urlOrPredicate, array $options = [])
 * @method-extended \NigelCunningham\Puphpeteer\Resources\Frame waitForFrame(string|callable(): |\NigelCunningham\Rialto\Data\JsFunction $urlOrPredicate, array $options = [])
 * @method \NigelCunningham\Puphpeteer\Resources\HTTPResponse|null goBack(array $options = [])
 * @method-extended \NigelCunningham\Puphpeteer\Resources\HTTPResponse|null goBack(array $options = [])
 * @method \NigelCunningham\Puphpeteer\Resources\HTTPResponse|null goForward(array $options = [])
 * @method-extended \NigelCunningham\Puphpeteer\Resources\HTTPResponse|null goForward(array $options = [])
 * @method void bringToFront()
 * @method-extended void bringToFront()
 * @method void emulate(array $options)
 * @method-extended void emulate(array{ viewport: mixed, userAgent: string } $options)
 * @method void setJavaScriptEnabled(bool $enabled)
 * @method-extended void setJavaScriptEnabled(bool $enabled)
 * @method void setBypassCSP(bool $enabled)
 * @method-extended void setBypassCSP(bool $enabled)
 * @method void emulateMediaType(string $type = null)
 * @method-extended void emulateMediaType(string $type = null)
 * @method void emulateCPUThrottling(float|null $factor)
 * @method-extended void emulateCPUThrottling(float|null $factor)
 * @method void emulateMediaFeatures(mixed[] $features = null)
 * @method-extended void emulateMediaFeatures(mixed[] $features = null)
 * @method void emulateTimezone(string $timezoneId = null)
 * @method-extended void emulateTimezone(string $timezoneId = null)
 * @method void emulateIdleState(array $overrides = [])
 * @method-extended void emulateIdleState(array{ isUserActive: bool, isScreenUnlocked: bool } $overrides = null)
 * @method void emulateVisionDeficiency(mixed $type = null)
 * @method-extended void emulateVisionDeficiency(mixed $type = null)
 * @method void setViewport(mixed $viewport)
 * @method-extended void setViewport(mixed $viewport)
 * @method mixed|null viewport()
 * @method-extended mixed|null viewport()
 * @method mixed evaluate(\NigelCunningham\Rialto\Data\JsFunction $pageFunction, int|float|string|bool|null|array|\NigelCunningham\Puphpeteer\Resources\JSHandle ...$args)
 * @method-extended mixed evaluate(callable|\NigelCunningham\Rialto\Data\JsFunction $pageFunction, int|float|string|bool|null|array|\NigelCunningham\Puphpeteer\Resources\JSHandle ...$args)
 * @method void evaluateOnNewDocument(\NigelCunningham\Rialto\Data\JsFunction|string $pageFunction, mixed ...$args)
 * @method-extended void evaluateOnNewDocument(callable|\NigelCunningham\Rialto\Data\JsFunction|string $pageFunction, mixed ...$args)
 * @method void setCacheEnabled(bool $enabled = null)
 * @method-extended void setCacheEnabled(bool $enabled = null)
 * @method mixed|string screenshot(array $options = [])
 * @method-extended mixed|string screenshot(array<string, mixed> $options = null)
 * @method mixed createPDFStream(array $options = [])
 * @method-extended mixed createPDFStream(array<string, mixed> $options = null)
 * @method mixed pdf(array $options = [])
 * @method-extended mixed pdf(array<string, mixed> $options = null)
 * @method string title()
 * @method-extended string title()
 * @method void close(array $options = [])
 * @method-extended void close(array{ runBeforeUnload: bool } $options = null)
 * @method bool isClosed()
 * @method-extended bool isClosed()
 * @method void click(string $selector, array $options = [])
 * @method-extended void click(string $selector, array{ delay: float, button: mixed, clickCount: float } $options = null)
 * @method void focus(string $selector)
 * @method-extended void focus(string $selector)
 * @method void hover(string $selector)
 * @method-extended void hover(string $selector)
 * @method string[] select(string $selector, string ...$values)
 * @method-extended string[] select(string $selector, string ...$values)
 * @method void tap(string $selector)
 * @method-extended void tap(string $selector)
 * @method void type(string $selector, string $text, array $options = [])
 * @method-extended void type(string $selector, string $text, array{ delay: float } $options = [])
 * @method \NigelCunningham\Puphpeteer\Resources\JSHandle waitFor(string|float|\NigelCunningham\Rialto\Data\JsFunction $selectorOrFunctionOrTimeout, array $options = [], int|float|string|bool|null|array|\NigelCunningham\Puphpeteer\Resources\JSHandle ...$args)
 * @method-extended \NigelCunningham\Puphpeteer\Resources\JSHandle waitFor(string|float|callable|\NigelCunningham\Rialto\Data\JsFunction $selectorOrFunctionOrTimeout, array{ visible: bool, hidden: bool, timeout: float, polling: string|float } $options = null, int|float|string|bool|null|array|\NigelCunningham\Puphpeteer\Resources\JSHandle ...$args)
 * @method void waitForTimeout(float $milliseconds)
 * @method-extended void waitForTimeout(float $milliseconds)
 * @method \NigelCunningham\Puphpeteer\Resources\ElementHandle|null waitForSelector(string $selector, array $options = [])
 * @method-extended \NigelCunningham\Puphpeteer\Resources\ElementHandle|null waitForSelector(string $selector, array{ visible: bool, hidden: bool, timeout: float } $options = null)
 * @method \NigelCunningham\Puphpeteer\Resources\ElementHandle|null waitForXPath(string $xpath, array $options = [])
 * @method-extended \NigelCunningham\Puphpeteer\Resources\ElementHandle|null waitForXPath(string $xpath, array{ visible: bool, hidden: bool, timeout: float } $options = null)
 * @method \NigelCunningham\Puphpeteer\Resources\JSHandle waitForFunction(\NigelCunningham\Rialto\Data\JsFunction|string $pageFunction, array $options = [], int|float|string|bool|null|array|\NigelCunningham\Puphpeteer\Resources\JSHandle ...$args)
 * @method-extended \NigelCunningham\Puphpeteer\Resources\JSHandle waitForFunction(callable|\NigelCunningham\Rialto\Data\JsFunction|string $pageFunction, array{ timeout: float, polling: string|float } $options = null, int|float|string|bool|null|array|\NigelCunningham\Puphpeteer\Resources\JSHandle ...$args)
 */
class Page extends EventEmitter
{
    use AliasesSelectionMethods, AliasesEvaluationMethods;
}
